### ISSUE TITLE
inputEncoding & outputEncoding options are not applied for `null`

### ISSUE THREAD

**Issue by kanongil** [broccolijs/broccoli-filter#47]
I need to process binary files as buffers. When I specify `inputEncoding: null` in the `super()` options, it is ignored and ends up reading the file as `utf8`.

If I manually set `this.inputEncoding = null` after the `super()` call, everything works fine.

**Comment by kanongil** [comment]
Ping? The documentation explicitly states that this should work, and it used to work but got broken with c14bc29226528c705954cd6ba650cb6a7d864d06.

**Comment by kanongil** [comment]
FYI, I use it here: https://github.com/kanongil/broccoli-imagemin/blob/master/lib/index.js

**Comment by joliss** [comment]
Thanks! A fix is out in v1.3.0.
